GET http://127.0.0.1:5000/lecturers

###
POST http://127.0.0.1:5000/lecturers
Content-Type: application/json

{
    "Username": "Amaw",
    "Password": "password123",
    "Full_Name": "Amaw Smith",
    "Email": "maw@gmail.com",
    "Phone_Number": "123-456-7890",
    "Position": "Lecturer",
    "Major": "Computer Science",
    "Profile": {
        "Date_of_birth": "1990-01-01",
        "gender": "Female",
        "Bio": "A lecturer in Computer Science",
        "Profile_Picture": "https://example.com/profile-picture.jpg"
    },
    "Teaching_History": [], 
    "Education_History": [], 
    "Research": [], 
    "PKM": [] 
}

###
POST http://localhost:5000/admin
Content-Type: application/json

{
    "nip" :"1982973286",
    "password" : "dosen12334",
    "role" : "Dosen"
}

###
GET http://localhost:5000/account

###
POST http://localhost:5000/lecturer
Content-Type: application/json

{
    "profile_picture" :"https://example.com/images/profile.jpg",
    "full_name" : "Bambang Wicak",
    "place_of_birth" : "Bandung",
    "date_of_birth" : "1989-09-09",
    "gender" : "Laki-Laki",
    "email" : "dosen1@gmail.com",
    "bio" : "Biooo",
    "id_user_account" : "1"
}